#!/bin/bash

echo "================================================================"
echo "DIAGNÓSTICO: PM2 online pero puerto no responde"
echo "================================================================"
echo ""
echo "Esto significa que la app inició pero probablemente crasheó."
echo ""
echo "EJECUTA ESTOS COMANDOS EN TU SERVIDOR:"
echo "================================================================"
echo ""
echo "# 1. Ver logs de PM2 (verás el error aquí)"
echo "pm2 logs walgreens-scanner --lines 50"
echo ""
echo "# 2. Ver estado detallado"
echo "pm2 show walgreens-scanner"
echo ""
echo "# 3. Ver errores específicos"
echo "pm2 logs walgreens-scanner --err --lines 30"
echo ""
echo "================================================================"
echo "ERRORES COMUNES:"
echo "================================================================"
echo ""
echo "Error: Cannot find module '@neondatabase/serverless'"
echo "  → Ejecuta: npm install"
echo ""
echo "Error: Cannot connect to database"
echo "  → Verifica DATABASE_URL en .env"
echo "  → Ejecuta: psql tu_database_url -c 'SELECT 1'"
echo ""
echo "Error: Port 5000 already in use"
echo "  → Encuentra qué usa el puerto: lsof -i:5000"
echo "  → Mátalo: kill -9 PID"
echo "  → O cambia PORT en .env"
echo ""
echo "================================================================"
echo "DESPUÉS DE VER LOS LOGS, COPIA EL ERROR AQUÍ"
echo "================================================================"
